
import __ASTRO_IMAGE_IMPORT_2uhPbu from "./spongebob.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-markdown-syntax%2Findex.md";
import __ASTRO_IMAGE_IMPORT_20fXAf from "./winning.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhandsign-post%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z29r2mt from "image-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1lWTjq from "image-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1ifKVj from "Screenshot 2025-09-21 at 6.44.09 PM.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_4gKAR from "image-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1uvqwa from "image-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
export default new Map([["./spongebob.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-markdown-syntax%2Findex.md", __ASTRO_IMAGE_IMPORT_2uhPbu], ["./winning.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhandsign-post%2Findex.md", __ASTRO_IMAGE_IMPORT_20fXAf], ["image-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_Z29r2mt], ["image-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1lWTjq], ["Screenshot 2025-09-21 at 6.44.09 PM.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1ifKVj], ["image-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_4gKAR], ["image-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_1uvqwa]]);
		