
import __ASTRO_IMAGE_IMPORT_Z29r2mt from "image-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1lWTjq from "image-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1LFrxT from "image6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_4gKAR from "image-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1uvqwa from "image-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_lqLCB from "image5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md";
import __ASTRO_IMAGE_IMPORT_20fXAf from "./winning.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhandsign-post%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1bSnr9 from "comp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zydtu4 from "m1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1yNuCd from "linear.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_23VCuC from "m3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_JQz0h from "m2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_18MXPH from "contextpill.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1i89zX from "stack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2rmY03 from "contextbar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_10t2bJ from "final.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Qroip from "final2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2uhPbu from "./spongebob.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-markdown-syntax%2Findex.md";
export default new Map([["image-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_Z29r2mt], ["image-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1lWTjq], ["image6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_1LFrxT], ["image-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_4gKAR], ["image-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_1uvqwa], ["image5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fchingu-setup%2Findex.md", __ASTRO_IMAGE_IMPORT_lqLCB], ["./winning.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhandsign-post%2Findex.md", __ASTRO_IMAGE_IMPORT_20fXAf], ["comp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1bSnr9], ["m1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_Zydtu4], ["linear.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_1yNuCd], ["m3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_23VCuC], ["m2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_JQz0h], ["contextpill.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_18MXPH], ["stack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_1i89zX], ["contextbar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2rmY03], ["final.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_10t2bJ], ["final2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fklue%2Findex.md", __ASTRO_IMAGE_IMPORT_Qroip], ["./spongebob.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-markdown-syntax%2Findex.md", __ASTRO_IMAGE_IMPORT_2uhPbu]]);
		